# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 641)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_success = QtWidgets.QLabel(self.centralwidget)
        self.file_success.setGeometry(QtCore.QRect(1020, 230, 271, 41))
        self.file_success.setText("")
        self.file_success.setObjectName("file_success")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 130, 801, 171))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_groups = QtWidgets.QLabel(self.frame)
        self.label_groups.setGeometry(QtCore.QRect(10, 10, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_groups.setFont(font)
        self.label_groups.setStyleSheet("")
        self.label_groups.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_groups.setObjectName("label_groups")
        self.groups = QtWidgets.QLineEdit(self.frame)
        self.groups.setGeometry(QtCore.QRect(400, 10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groups.setFont(font)
        self.groups.setObjectName("groups")
        self.add_groups = QtWidgets.QPushButton(self.frame)
        self.add_groups.setGeometry(QtCore.QRect(10, 90, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_groups.setFont(font)
        self.add_groups.setObjectName("add_groups")
        self.random_data = QtWidgets.QPushButton(self.frame)
        self.random_data.setGeometry(QtCore.QRect(600, 10, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.random_data.setFont(font)
        self.random_data.setObjectName("random_data")
        self.begin = QtWidgets.QPushButton(self.frame)
        self.begin.setGeometry(QtCore.QRect(600, 90, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.begin.setFont(font)
        self.begin.setObjectName("begin")
        self.label_groups_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_groups_2.setGeometry(QtCore.QRect(200, 90, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_groups_2.setFont(font)
        self.label_groups_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_groups_2.setObjectName("label_groups_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(200, 390, 801, 151))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.scenarios = QtWidgets.QComboBox(self.frame_2)
        self.scenarios.setGeometry(QtCore.QRect(10, 20, 561, 61))
        self.scenarios.setObjectName("scenarios")
        self.edit = QtWidgets.QPushButton(self.frame_2)
        self.edit.setGeometry(QtCore.QRect(320, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edit.setFont(font)
        self.edit.setObjectName("edit")
        self.update = QtWidgets.QPushButton(self.frame_2)
        self.update.setGeometry(QtCore.QRect(450, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.update.setFont(font)
        self.update.setObjectName("update")
        self.play = QtWidgets.QPushButton(self.frame_2)
        self.play.setGeometry(QtCore.QRect(600, 20, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.play.setFont(font)
        self.play.setObjectName("play")
        self.label_groups_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_groups_3.setGeometry(QtCore.QRect(200, 340, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_groups_3.setFont(font)
        self.label_groups_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_groups_3.setObjectName("label_groups_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1323, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scenario Generator"))
        self.label_groups.setText(_translate("MainWindow", "No. of Groups"))
        self.add_groups.setText(_translate("MainWindow", "Add groups info"))
        self.begin.setText(_translate("MainWindow", "Create New"))
        self.random_data.setText(_translate("MainWindow", "Large Data"))
        self.label_groups_2.setText(_translate("MainWindow", "Create New Scenario : "))
        self.edit.setText(_translate("MainWindow", "Edit"))
        self.update.setText(_translate("MainWindow", "Update"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.label_groups_3.setText(_translate("MainWindow", "Edit / Play Scenario:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainPage()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

